"""empty message

Revision ID: f861c271a9cb
Revises: 
Create Date: 2021-12-13 13:39:43.191191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f861c271a9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_lv1', sa.String(length=20), nullable=False),
    sa.Column('tech_lv2', sa.String(length=20), nullable=False),
    sa.Column('tech_lv3', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_dict')
    # ### end Alembic commands ###
